name: kafka-oreily-codes

services:
  kafka:
    image: apache/kafka:3.7.0
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: always
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

volumes:
    kafka-data:
